- name: Add disks to virtual machine
  vmware_guest_disk:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ head_worker }}"
    disk:
      - size_gb: "{{ disk_size }}"
        type: eagerzeroedthick
        state: present
        autoselect_datastore: True
        scsi_controller: 1
        unit_number: 0
  delegate_to: localhost
